
name: pytest_push

on:
  push:
    branches: [ master ]

jobs:
  tester:
    runs-on: ubuntu-latest

    steps:
    # Checks-out under $GITHUB_WORKSPACE, so job can access it
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v1
      with: 
            python-version: '3.x'
    
    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip # This path is specific to Ubuntu
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
      
    - name: Install dependencies
      run: pip install -r rlrequirements.txt
      
    - name: Test with pytest
      run: |
        echo "::set-env name=PYTHONPATH::home/runner/work/rl-rubiks/rl-rubiks"
        pip install pytest
        pytest
